/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//3. Use TIM7 to generate interrupt after every 1 second. Increment a global count in interrupt handler. Display count value on LCD (I2C based).
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "i2c_lcd.h"
#include "timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern volatile uint8_t gcnt;
char str [4];
int main(void)
{
	SystemInit();
	I2CInit();
	LcdInit();

	LcdPuts(LCD_LINE1,"count");

	//extern volatile uint8_t gcnt =0;// global counter to update in interrupt
	TimerInit(1000);
	while(1) {
		//LcdPuts(LCD_LINE2,gcnt);
		//TimerInit(1000);
		sprintf(str,"%d",gcnt);
		LcdPuts(LCD_LINE2,str);
	}
	return 0;
}


